### Import Game Stats

In [1]:
import pandas as pd
import numpy as np
import joblib  # Assuming model was saved using joblib
import os
from datetime import datetime

# Load the trained model
model_path = "./best_xgb_model.pkl"  # Ensure the correct model path
best_xgb = joblib.load(model_path)

# Enter a date in MM-DD-YYYY format for upcoming NBA games
game_day = "03-28-2025"

In [2]:
try:
    user_date = datetime.strptime(game_day, "%m-%d-%Y")
except ValueError:
    print("Incorrect date format. Please use MM-DD-YYYY.")
    exit()

# Determine the NBA season based on the input date.
# Rule: If the month is before July, then the season is the previous year; otherwise, it's the current year.
if user_date.month < 7:
    season = user_date.year - 1
else:
    season = user_date.year

print(f"Determined NBA season: {season}")

# Construct the file path for the appropriate season's games CSV file
file_path = f"./New_data/nba_games_{season}.csv"

# Check if the file exists
if not os.path.exists(file_path):
    print(f"Error: {file_path} does not exist. Please ensure the file is present.")
    exit()

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Convert the 'date' column to datetime format for comparison
df["date"] = pd.to_datetime(df["date"])

# Filter the DataFrame to only include rows with the user-provided date
upcoming_games = df[df["date"] == user_date]

# Keep only the desired columns
columns_to_keep = [
    "id", "date", "season", "home_team_full_name",
    "visitor_team_full_name", "home_team_city", "postseason"
]
upcoming_games = upcoming_games[columns_to_keep]

# Rename columns as required:
# - "id" -> "game_id"
# - "home_team_full_name" -> "home_team"
# - "visitor_team_full_name" -> "away_team"
# - "home_team_city" -> "game_city"
# - "postseason" -> "game_postseason"
upcoming_games.rename(columns={
    "id": "game_id",
    "home_team_full_name": "home_team",
    "visitor_team_full_name": "away_team",
    "home_team_city": "game_city",
    "postseason": "game_postseason"
}, inplace=True)

# Display the filtered DataFrame
print(f"\nNBA Games on {game_day} ")
upcoming_games

Determined NBA season: 2024

NBA Games on 03-28-2025

,game_id,date,season,home_team,away_team,game_city,game_postseason
1107,15908799,2025-03-28,2024,Brooklyn Nets,LA Clippers,Brooklyn,False
1108,15908801,2025-03-28,2024,Milwaukee Bucks,New York Knicks,Milwaukee,False
1109,15908804,2025-03-28,2024,Denver Nuggets,Utah Jazz,Denver,False
1110,15908803,2025-03-28,2024,New Orleans Pelicans,Golden State Warriors,New Orleans,False
1111,15908802,2025-03-28,2024,Minnesota Timberwolves,Phoenix Suns,Minnesota,False
1112,15908798,2025-03-28,2024,Detroit Pistons,Cleveland Cavaliers,Detroit,False
1113,15908800,2025-03-28,2024,Toronto Raptors,Charlotte Hornets,Toronto,False

In [3]:
# Import historical data
merged_df = pd.read_csv("./game_stats_with_box_scores_merged.csv")

merged_df

,date,season,status,home_team_id,home_team,visitor_team_id,visitor_team,home_score,visitor_score,player_id,...,game_id,game_period,game_postseason,is_absent,minutes_rolling15,pie_rolling15,usage_percentage_rolling15,net_rating_rolling15,pts_rolling15,player_importance
0,2021-01-06,2020,Final,17,Milwaukee Bucks,9,Detroit Pistons,130,115,2,...,127617.0,4.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-03,2020,Final,17,Milwaukee Bucks,12,Indiana Pacers,130,110,2,...,127830.0,4.0,False,False,0.950000,-1.00000,0.333000,-100.0,0.0,-14.770050
2,2021-02-05,2020,Final,6,Cleveland Cavaliers,17,Milwaukee Bucks,105,123,2,...,127843.0,4.0,False,False,4.708333,-0.52500,0.257500,-87.5,0.0,-11.308042
3,2021-02-06,2020,Final,6,Cleveland Cavaliers,17,Milwaukee Bucks,99,124,2,...,127858.0,4.0,False,False,3.700000,-0.35000,0.171667,-25.0,0.0,-2.314250
4,2021-02-08,2020,Final,8,Denver Nuggets,17,Milwaukee Bucks,112,125,2,...,127875.0,4.0,False,False,4.025000,-0.17925,0.203750,-20.7,0.5,-1.450287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159686,2025-02-23,2024,Final,10,Golden State Warriors,7,Dallas Mavericks,126,102,1042461962,...,15908543.0,4.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN
159687,2025-02-25,2024,Final,10,Golden State Warriors,4,Charlotte Hornets,128,92,1042461962,...,15908565.0,4.0,False,False,6.000000,0.01900,0.176000,-34.3,2.0,-2.514800
159688,2025-02-20,2024,Final,3,Brooklyn Nets,6,Cleveland Cavaliers,97,110,1042560902,...,15908522.0,4.0,False,False,NaN,NaN,NaN,NaN,NaN,NaN
159689,2025-02-21,2024,Final,6,Cleveland Cavaliers,20,New York Knicks,142,105,1042560902,...,15908528.0,4.0,False,False,3.000000,0.12100,0.250000,-111.9,3.0,-15.223300
159690,2025-02-25,2024,Final,22,Orlando Magic,6,Cleveland Cavaliers,82,122,1042560902,...,15908561.0,4.0,False,False,5.000000,0.11900,0.256500,-52.6,4.0,-5.427725

In [4]:
file_path = "./team_absent_impact.csv"

team_absent_impact = pd.read_csv(file_path)

team_absent_impact

      team_id     game_id  team_absent_impact
0         1.0    127528.0           19.892750
1         1.0    127542.0           11.617575
2         1.0    127559.0            1.114133
3         1.0    127574.0            4.882413
4         1.0    127596.0            4.065839
...       ...         ...                 ...
8495     30.0  15908546.0            5.215983
8496     30.0  15908625.0            9.405610
8497     30.0  15908714.0            0.371270
8498     30.0  16968277.0            7.643282
8499     30.0  16968286.0            0.225956

[8500 rows x 3 columns]

In [5]:
# Import historical data
team_aggregated_df = pd.read_csv("./team_aggregated_game_data.csv")

# **Merge impact of absent players per team per game to team_aggregated_df
team_aggregated_df = team_aggregated_df.merge(
    team_absent_impact, on=["team_id", "game_id"], how="left"
)
# Fill NaN values (if no absences, impact should be 0)
team_aggregated_df["team_absent_impact"] = team_aggregated_df["team_absent_impact"].fillna(0)

team_aggregated_df

,game_id,date,season,team_id,team_name,is_home_game,game_postseason,game_won,team_points,point_diff,...,turnover,turnover_ratio,pf,pace,net_rating,offensive_rating,defensive_rating,usage_percentage,absent_players,team_absent_impact
0,127502.0,2020-12-22,2020,3,Brooklyn Nets,True,0,1,125,26,...,20.0,13.460000,22.0,111.008667,3.000000,103.086667,100.106667,0.183067,0,0.000000
1,127502.0,2020-12-22,2020,10,Golden State Warriors,False,0,0,99,26,...,18.0,11.415385,24.0,112.133077,-15.392308,92.638462,108.061538,0.181615,0,0.000000
2,127503.0,2020-12-22,2020,13,LA Clippers,False,0,1,116,7,...,16.0,7.000000,29.0,87.358000,-29.073333,69.313333,98.386667,0.165800,2,0.000000
3,127503.0,2020-12-22,2020,14,Los Angeles Lakers,True,0,0,109,7,...,19.0,15.691667,20.0,103.020000,6.150000,113.800000,107.641667,0.163833,0,0.000000
4,127504.0,2020-12-23,2020,4,Charlotte Hornets,False,0,0,114,7,...,15.0,10.475000,17.0,85.930833,-7.191667,91.908333,99.075000,0.157917,2,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12171,17136019.0,2024-12-15,2024,22,Orlando Magic,True,0,0,91,9,...,15.0,9.218750,26.0,81.619375,-3.000000,81.250000,84.243750,0.139813,3,0.000000
12172,17136020.0,2024-12-15,2024,7,Dallas Mavericks,False,0,1,143,10,...,15.0,7.200000,12.0,88.007333,-0.260000,80.866667,81.120000,0.108467,3,0.000000
12173,17136020.0,2024-12-15,2024,10,Golden State Warriors,True,0,0,133,10,...,10.0,2.937500,17.0,72.695000,-1.756250,82.531250,84.312500,0.111875,5,3.087053
12174,17195500.0,2024-12-17,2024,17,Milwaukee Bucks,False,0,1,97,16,...,17.0,6.750000,20.0,77.445625,-21.231250,56.906250,78.150000,0.143000,3,7.425643
12175,17195500.0,2024-12-17,2024,21,Oklahoma City Thunder,True,0,0,81,16,...,10.0,6.140000,14.0,76.754000,-6.433333,66.260000,72.700000,0.137800,3,0.000000

### Aggregate player-game data to Team-game data

#### Import Injured Player List

In [6]:
# Import current player injury data from csv file
df_injury = pd.read_csv("./New_data/injured_players_cleaned.csv") 

# Display all columns
df_injury

     player_id
0           83
1   1028246478
2          340
3     17896040
4     56677838
..         ...
78    56677824
79    56677845
80    56677844
81          65
82     3547256

[83 rows x 1 columns]

In [7]:
# Import current player data from csv file
df_players = pd.read_csv("./New_data/nba_active_players.csv") 

# Display all columns
absent_counts = df_players[df_players["id"].isin(df_injury["player_id"])].groupby("team_full_name")["id"].count()

absent_counts

team_full_name
Atlanta Hawks             5
Boston Celtics            1
Chicago Bulls             3
Dallas Mavericks          8
Denver Nuggets            3
Detroit Pistons           1
Golden State Warriors     2
Houston Rockets           2
Indiana Pacers            1
LA Clippers               4
Los Angeles Lakers        4
Memphis Grizzlies         3
Miami Heat                2
New Orleans Pelicans      3
New York Knicks           2
Oklahoma City Thunder     4
Orlando Magic             2
Philadelphia 76ers        8
Phoenix Suns              3
Portland Trail Blazers    3
Sacramento Kings          1
San Antonio Spurs         3
Toronto Raptors           9
Utah Jazz                 2
Washington Wizards        4
Name: id, dtype: int64

In [8]:
# Step 1: Get list of injured player_ids
injured_player_ids = df_players[df_players["id"].isin(df_injury["player_id"])]["id"]

# Step 2: Filter merged_df for injured players and get most recent entry per player
recent_importance = (
    merged_df[merged_df["player_id"].isin(injured_player_ids)]
    .sort_values("date", ascending=False)
    .drop_duplicates("player_id", keep="first")[["player_id", "player_importance"]]
    .set_index("player_id")["player_importance"]
)

# Step 3: Display or use the result
recent_importance

player_id
56677845       1.858830
274           11.202045
65             3.760250
56677844      13.997263
358            8.061892
                ...
1028245994          NaN
17896035       5.837130
56677824       9.865477
3547256             NaN
56677855      -0.738819
Name: player_importance, Length: 81, dtype: float64

In [9]:
# 1. Filter most recent importance values for injured players
recent_importance_with_team = (
    merged_df[merged_df["player_id"].isin(injured_player_ids)]
    .sort_values("date", ascending=False)
    .drop_duplicates("player_id", keep="first")[["player_id", "player_importance", "team"]]
)

# 2. Group by team and sum player_importance
total_importance_by_team = recent_importance_with_team.groupby("team")["player_importance"].sum()

# 3. Display result
total_importance_by_team.sort_values(ascending=False)

team
Toronto Raptors           55.313432
Los Angeles Lakers        40.355643
Philadelphia 76ers        35.707977
Dallas Mavericks          33.992371
Oklahoma City Thunder     25.569891
Chicago Bulls             25.467391
Atlanta Hawks             23.863272
Utah Jazz                 21.427260
Washington Wizards        19.616343
Houston Rockets           19.064803
Denver Nuggets            18.792604
LA Clippers               18.416703
Memphis Grizzlies         18.277825
New York Knicks           17.298109
Portland Trail Blazers    17.069423
Phoenix Suns              16.730276
Golden State Warriors     13.238780
Miami Heat                11.912960
Sacramento Kings          11.077695
New Orleans Pelicans       8.061892
Boston Celtics             7.800597
Indiana Pacers             5.837130
San Antonio Spurs          5.010700
Orlando Magic              0.000000
Detroit Pistons            0.000000
Name: player_importance, dtype: float64

In [10]:
# Step 1: Create copies for home and away rows
home_rows = upcoming_games.copy()
away_rows = upcoming_games.copy()

# Step 2: Build a mapping from (team_name + season) to team_id
lookup_df = team_aggregated_df[["team_name", "season", "team_id"]].drop_duplicates()
home_rows = home_rows.merge(lookup_df, left_on=["home_team", "season"], right_on=["team_name", "season"], how="left")
home_rows["team_name"] = home_rows["home_team"]
home_rows["is_home_game"] = True

away_rows = away_rows.merge(lookup_df, left_on=["away_team", "season"], right_on=["team_name", "season"], how="left")
away_rows["team_name"] = away_rows["away_team"]
away_rows["is_home_game"] = False

# Step 3: Keep only relevant columns that exist in team_aggregated_df
shared_cols = list(set(home_rows.columns) & set(team_aggregated_df.columns))
home_rows = home_rows[shared_cols]
away_rows = away_rows[shared_cols]

# Step 4: Add number of absent players for each team
home_rows["absent_players"] = home_rows["team_name"].map(absent_counts).fillna(0).astype(int)
away_rows["absent_players"] = away_rows["team_name"].map(absent_counts).fillna(0).astype(int)

# Step 5: Add impact of absent players for each team
home_rows["team_absent_impact"] = home_rows["team_name"].map(total_importance_by_team).fillna(0).astype(int)
away_rows["team_absent_impact"] = away_rows["team_name"].map(total_importance_by_team).fillna(0).astype(int)

# Step 6: Combine and append
upcoming_rows = pd.concat([home_rows, away_rows], ignore_index=True)
team_aggregated_df = pd.concat([team_aggregated_df, upcoming_rows], ignore_index=True)

# Step 7: Optional - re-sort and reset index
team_aggregated_df["date"] = pd.to_datetime(team_aggregated_df["date"])
team_aggregated_df.sort_values("date", inplace=True)
team_aggregated_df.reset_index(drop=True, inplace=True)

In [11]:
team_aggregated_df[team_aggregated_df["team_absent_impact"] > 0]

,game_id,date,season,team_id,team_name,is_home_game,game_postseason,game_won,team_points,point_diff,...,turnover,turnover_ratio,pf,pace,net_rating,offensive_rating,defensive_rating,usage_percentage,absent_players,team_absent_impact
32,127519.0,2020-12-25,2020,19,New Orleans Pelicans,False,0,0.0,98.0,13.0,...,19.0,10.946154,20.0,67.540769,-20.361538,68.569231,88.930769,0.128308,4,0.389250
37,127519.0,2020-12-25,2020,16,Miami Heat,True,0,1.0,111.0,13.0,...,17.0,8.485714,25.0,80.497143,7.535714,80.407143,72.878571,0.130214,2,5.550483
41,127530.0,2020-12-26,2020,25,Portland Trail Blazers,True,0,1.0,128.0,2.0,...,13.0,8.581818,20.0,89.513636,-10.045455,95.454545,105.490909,0.157000,1,1.968800
43,127529.0,2020-12-26,2020,28,Toronto Raptors,False,0,0.0,114.0,5.0,...,11.0,5.160000,23.0,63.507333,-5.400000,60.933333,66.320000,0.118400,6,31.113067
46,127528.0,2020-12-26,2020,1,Atlanta Hawks,False,0,1.0,122.0,10.0,...,15.0,9.858333,20.0,88.295000,4.200000,95.258333,91.058333,0.160000,2,19.892750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12179,15908801.0,2025-03-28,2024,20,New York Knicks,False,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,17.000000
12180,15908799.0,2025-03-28,2024,13,LA Clippers,False,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,18.000000
12181,15908800.0,2025-03-28,2024,28,Toronto Raptors,True,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,55.000000
12182,15908803.0,2025-03-28,2024,19,New Orleans Pelicans,True,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8.000000
12184,15908804.0,2025-03-28,2024,8,Denver Nuggets,True,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,18.000000

In [12]:
# Ensure sorting by team_id and date
team_aggregated_df.sort_values(by=["team_id", "date"], inplace=True)

# 1. For each team, compute difference in days between consecutive games within a season
team_aggregated_df.sort_values(by=["team_id", "date"], inplace=True)

team_aggregated_df['days_since_last_game'] = (
    team_aggregated_df.groupby(["team_id", "season"])["date"]
      .diff()
      .dt.days
)

# 2. Compute Win Streak (positive for winning streaks, negative for losing streaks)
def compute_win_streak(series):
    streak = (series.shift(1) * 2 - 1)  # Convert 1 -> 1 (win), 0 -> -1 (loss)
    return streak.groupby((streak != streak.shift()).cumsum()).cumcount() * streak
# Apply function and reset index to avoid misalignment issues
team_aggregated_df["win_streak"] = (
    team_aggregated_df.groupby("team_id")["game_won"]
    .apply(compute_win_streak)
    .reset_index(level=0, drop=True)  # Ensures correct indexing
)

# Sort by date before updating ELO:
team_aggregated_df.sort_values(by=["season", "date"], inplace=True)

# 3. Compute ELO Rating
def update_elo(elo_a, elo_b, score_a, k=20):
    """ELO rating update function"""
    expected_a = 1 / (1 + 10 ** ((elo_b - elo_a) / 400))
    change = k * (score_a - expected_a)
    return elo_a + change, elo_b - change

# Initialize Elo ratings
initial_elo = 1500
elo_ratings_all_time = {team: initial_elo for team in team_aggregated_df["team_id"].unique()}
season_elo_ratings = {}  # Dictionary to track season-based Elo ratings

team_aggregated_df["team_elo"] = np.nan  # All-time Elo
team_aggregated_df["opponent_elo"] = np.nan
team_aggregated_df["season_elo"] = np.nan  # Elo that resets each season
team_aggregated_df["opponent_season_elo"] = np.nan  # Opponent's season Elo

# Process ELO updates
for index, row in team_aggregated_df.iterrows():
    team_id = row["team_id"]
    game_id = row["game_id"]
    season = row["season"]

    # Reset season Elo ratings at the start of each season
    if season not in season_elo_ratings:
        season_elo_ratings[season] = {team: initial_elo for team in team_aggregated_df["team_id"].unique()}

    # Find opponent
    opponent = team_aggregated_df[(team_aggregated_df["game_id"] == game_id) & 
                                  (team_aggregated_df["team_id"] != team_id)]

    if not opponent.empty:
        opponent_id = opponent.iloc[0]["team_id"]

        # Assign all-time Elo ratings
        if pd.isna(team_aggregated_df.at[index, "team_elo"]):
            team_aggregated_df.at[index, "team_elo"] = elo_ratings_all_time.get(team_id, initial_elo)
        if pd.isna(team_aggregated_df.at[index, "opponent_elo"]):
            team_aggregated_df.at[index, "opponent_elo"] = elo_ratings_all_time.get(opponent_id, initial_elo)

        # Assign season Elo ratings
        if pd.isna(team_aggregated_df.at[index, "season_elo"]):
            team_aggregated_df.at[index, "season_elo"] = season_elo_ratings[season].get(team_id, initial_elo)
        if pd.isna(team_aggregated_df.at[index, "opponent_season_elo"]):
            team_aggregated_df.at[index, "opponent_season_elo"] = season_elo_ratings[season].get(opponent_id, initial_elo)

        # Get current ELOs
        team_elo = team_aggregated_df.at[index, "team_elo"]
        opponent_elo = team_aggregated_df.at[index, "opponent_elo"]

        season_elo = team_aggregated_df.at[index, "season_elo"]
        opponent_season_elo = team_aggregated_df.at[index, "opponent_season_elo"]

        # Update Elo based on game result
        score_a = 1 if row["game_won"] else 0
        new_team_elo, new_opponent_elo = update_elo(team_elo, opponent_elo, score_a)
        new_season_team_elo, new_season_opponent_elo = update_elo(season_elo, opponent_season_elo, score_a)

        # Update dictionaries
        elo_ratings_all_time[team_id] = new_team_elo
        elo_ratings_all_time[opponent_id] = new_opponent_elo

        season_elo_ratings[season][team_id] = new_season_team_elo
        season_elo_ratings[season][opponent_id] = new_season_opponent_elo

# 4. Compute Time-in-Season (Days since the first game of the season)
season_start_dates = team_aggregated_df.groupby("season")["date"].min().to_dict()
team_aggregated_df["time_in_season"] = team_aggregated_df.apply(lambda row: (row["date"] - season_start_dates[row["season"]]).days +1, axis=1)

In [13]:
# Display subset of data for visual validation
selected_columns = [
    "game_id", "date", "season", "team_id", "team_name", "is_home_game",
    "game_postseason", "game_won", "win_streak", "team_elo", "opponent_elo",
    "season_elo", "opponent_season_elo", "time_in_season"
]

# Filter for team_id 2 in season 2024 and select only the specified columns
filtered_df = team_aggregated_df.loc[
    (team_aggregated_df["team_id"] == 23) & (team_aggregated_df["season"] == 2024),
    selected_columns
]

# Display the filtered dataframe
filtered_df

,game_id,date,season,team_id,team_name,is_home_game,game_postseason,game_won,win_streak,team_elo,opponent_elo,season_elo,opponent_season_elo,time_in_season
10245,15907443.0,2024-10-23,2024,23,Philadelphia 76ers,True,0,0.0,-0.0,1549.803955,1503.082981,1490.000000,1510.000000,2
10278,15907455.0,2024-10-25,2024,23,Philadelphia 76ers,False,0,0.0,-1.0,1538.467264,1257.913406,1480.575011,1480.575011,4
10309,15907474.0,2024-10-27,2024,23,Philadelphia 76ers,False,0,1.0,-2.0,1517.479100,1557.441778,1472.201948,1486.781429,6
10355,15907497.0,2024-10-30,2024,23,Philadelphia 76ers,True,0,0.0,0.0,1511.589325,1241.935873,1471.159441,1442.925375,9
10406,15907519.0,2024-11-02,2024,23,Philadelphia 76ers,True,0,0.0,-0.0,1481.512556,1378.829369,1451.351355,1504.303128,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12036,15908607.0,2025-03-03,2024,23,Philadelphia 76ers,True,0,0.0,0.0,1371.090880,1527.004662,1371.046638,1534.845958,133
12055,15908618.0,2025-03-04,2024,23,Philadelphia 76ers,False,0,0.0,-0.0,1354.939866,1563.008803,1354.972713,1550.630517,134
12088,15908631.0,2025-03-06,2024,23,Philadelphia 76ers,False,0,0.0,-1.0,1347.896329,1698.336666,1347.411287,1678.066863,136
12143,15908655.0,2025-03-09,2024,23,Philadelphia 76ers,True,0,1.0,-2.0,1345.548353,1294.392155,1344.816819,1302.291471,139
12144,15908659.0,2025-03-10,2024,23,Philadelphia 76ers,False,0,0.0,0.0,1355.692581,1497.359346,1355.562593,1502.203299,140

In [14]:
# Import NBA games basic data

import glob

# Define the file path pattern for multiple seasons
file_pattern = "./New_data/nba_games_*.csv"

# Get list of all matching CSV files
csv_files = glob.glob(file_pattern)

# Load and combine all CSV files into a single DataFrame excluding game_time column as it's causing an error due to inconsistent data types
df_list = [pd.read_csv(file) for file in csv_files]
nba_games = pd.concat(df_list, ignore_index=True)

# Drop duplicated rows
nba_games = nba_games.drop_duplicates()

# Display basic information
nba_games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6279 entries, 0 to 6399
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         6279 non-null   int64
 1   date                       6279 non-null   object
 2   season                     6279 non-null   int64
 3   status                     6279 non-null   object
 4   period                     6279 non-null   float64
 5   time                       3573 non-null   object
 6   postseason                 6279 non-null   bool
 7   home_team_score            6279 non-null   float64
 8   visitor_team_score         6279 non-null   float64
 9   home_team_id               0 non-null      float64
 10  home_team_conference       6279 non-null   object
 11  home_team_division         6279 non-null   object
 12  home_team_city             6279 non-null   object
 13  home_team_name             6279 non-null   object
 14  home_team_full_name        6279 non-null   object
 15  home_team_abbreviation     6279 non-null   object
 16  visitor_team_id            0 non-null      float64
 17  visitor_team_conference    6279 non-null   object
 18  visitor_team_division      6279 non-null   object
 19  visitor_team_city          6279 non-null   object
 20  visitor_team_name          6279 non-null   object
 21  visitor_team_full_name     6279 non-null   object
 22  visitor_team_abbreviation  6279 non-null   object
dtypes: bool(1), float64(5), int64(2), object(15)
memory usage: 1.1+ MB

In [15]:
# Merge home_team_city from nba_games into team_aggregated_df based on game_id
team_aggregated_df = team_aggregated_df.merge(
    nba_games[["id", "home_team_city"]],  # Select relevant columns from nba_games
    left_on="game_id", 
    right_on="id", 
    how="left"
)

# Rename the merged column to "game_city"
team_aggregated_df.rename(columns={"home_team_city": "game_city"}, inplace=True)

# Drop redundant 'id' column from nba_games after merge
team_aggregated_df.drop(columns=["id"], inplace=True)

In [16]:
# Fix city names
city_mapping = {
    "Utah": "Salt Lake City",
    "Minnesota": "Minneapolis",
    "LA": "Los Angeles",
    "Golden State": "San Francisco",
    "Indiana": "Indianapolis"
}

# Apply the mapping
team_aggregated_df["game_city"] = team_aggregated_df["game_city"].replace(city_mapping)

In [17]:
# Lat & lon for NBA team cities
city_coords = {
    "Atlanta": (33.7490, -84.3880),
    "Boston": (42.3601, -71.0589),
    "Brooklyn": (40.6782, -73.9442),
    "Charlotte": (35.2271, -80.8431),
    "Chicago": (41.8781, -87.6298),
    "Cleveland": (41.4993, -81.6944),
    "Dallas": (32.7767, -96.7970),
    "Denver": (39.7392, -104.9903),
    "Detroit": (42.3314, -83.0458),
    "Houston": (29.7604, -95.3698),
    "Indianapolis": (39.7684, -86.1581),
    "Los Angeles": (34.0522, -118.2437),
    "Memphis": (35.1495, -90.0490),
    "Miami": (25.7617, -80.1918),
    "Milwaukee": (43.0389, -87.9065),
    "Minneapolis": (44.9778, -93.2650),
    "New Orleans": (29.9511, -90.0715),
    "New York": (40.7128, -74.0060),
    "Oklahoma City": (35.4676, -97.5164),
    "Orlando": (28.5383, -81.3792),
    "Philadelphia": (39.9526, -75.1652),
    "Phoenix": (33.4484, -112.0740),
    "Portland": (45.5152, -122.6784),
    "Sacramento": (38.5816, -121.4944),
    "San Antonio": (29.4241, -98.4936),
    "Salt Lake City": (40.7608, -111.8910),
    "San Francisco": (37.7749, -122.4194),
    "Toronto": (43.651070, -79.347015),
    "Washington": (38.9072, -77.0369)
}

# Extract unique non-null game_city values
unique_game_cities = team_aggregated_df["game_city"].dropna().unique()

# Find cities that are not in city_coords
missing_cities = [city for city in unique_game_cities if city not in city_coords]

# Display results
if missing_cities:
    print("❌ The following cities are missing from city_coords:", missing_cities)
else:
    print("✅ All game_city values are present in city_coords.")

✅ All game_city values are present in city_coords.

In [18]:
# Infer missing values for game_city values:

# Create a Mapping: team_id -> home_city (from rows where is_home_game is true)
home_games = team_aggregated_df[(team_aggregated_df['is_home_game'] == 1) & (team_aggregated_df['game_city'].notna())]
team_home_city = home_games.groupby('team_id')['game_city'].first().to_dict()
print("Team Home City Mapping (sample):", dict(list(team_home_city.items())[:5]))

# Fill Missing game_city for Home Games Using the Mapping
mask_home_missing = (team_aggregated_df['is_home_game'] == 1) & (team_aggregated_df['game_city'].isna())
team_aggregated_df.loc[mask_home_missing, 'game_city'] = team_aggregated_df.loc[mask_home_missing, 'team_id'].map(team_home_city)

# Fill Missing game_city for Remaining Rows by Grouping by game_id 
team_aggregated_df['game_city'] = team_aggregated_df.groupby('game_id')['game_city'].transform(lambda x: x.ffill().bfill())

# Report Missing Values
missing_after = team_aggregated_df['game_city'].isna().sum()
print("Missing game_city count after filling:", missing_after)

Team Home City Mapping (sample): {1: 'Atlanta', 2: 'Boston', 3: 'Brooklyn', 4: 'Charlotte', 5: 'Chicago'}
Missing game_city count after filling: 0

In [19]:
from geopy.distance import geodesic
import numpy as np

# Ensure dataset is sorted by team_id, season, and date
team_aggregated_df.sort_values(["team_id", "season", "date"], inplace=True)

# Function to calculate travel distance using city_coords dictionary
def calc_travel_distance(row):
    # Get current and previous game city
    current_city = row["game_city"]
    prev_city = row["prev_game_city"]

    # If it's the first game of the season or game_city is missing/null, return NaN
    if pd.isna(prev_city) or pd.isna(current_city):
        return np.nan  # Return NaN instead of 0

    # Get coordinates from city_coords dictionary
    if current_city in city_coords and prev_city in city_coords:
        lat1, lon1 = city_coords[prev_city]
        lat2, lon2 = city_coords[current_city]
        return int(round(geodesic((lat1, lon1), (lat2, lon2)).miles))  # Convert to integer miles

    return np.nan  # Return NaN if cities are not found in city_coords

# Create a column for the "previous" game city per team per season
team_aggregated_df["prev_game_city"] = (
    team_aggregated_df.groupby(["team_id", "season"])["game_city"].shift(1)
)

# Apply the function to calculate travel distance
team_aggregated_df["travel_distance"] = team_aggregated_df.apply(calc_travel_distance, axis=1)

print("✅ Travel distances calculated in miles. First game of season or missing city returns NaN!")

✅ Travel distances calculated in miles. First game of season or missing city returns NaN!

In [20]:
# Display the number of missing values for each column
missing_values = team_aggregated_df.isnull().sum()
print("Missing values for each column:")
print(missing_values)

Missing values for each column:
game_id                              0
date                                 0
season                               0
team_id                              0
team_name                            0
is_home_game                         0
game_postseason                      0
game_won                            14
team_points                         14
point_diff                          14
minutes                             14
pts                                 14
pie                                 14
field_goals_made                    14
field_goals_attempted               14
field_goal_percentage               14
three_pointers_made                 14
three_pointers_attempted            14
three_point_percentage              14
free_throws_made                    14
free_throws_attempted               14
free_throw_percentage               14
effective_field_goal_percentage     14
true_shooting_percentage            14
oreb                                14
dreb                                14
reb                                 14
offensive_rebound_percentage        14
defensive_rebound_percentage        14
rebound_percentage                  14
ast                                 14
assist_percentage                   14
assist_ratio                        14
assist_to_turnover                  14
stl                                 14
blk                                 14
turnover                            14
turnover_ratio                      14
pf                                  14
pace                                14
net_rating                          14
offensive_rating                    14
defensive_rating                    14
usage_percentage                    14
absent_players                       0
team_absent_impact                   0
days_since_last_game               150
win_streak                          30
team_elo                             0
opponent_elo                         0
season_elo                           0
opponent_season_elo                  0
time_in_season                       0
game_city                            0
prev_game_city                     150
travel_distance                    150
dtype: int64

In [21]:
# Create 15-game rolling average team performance metrics

# Sort by team_id, then by date
team_aggregated_df.sort_values(by=["team_id", "date"], inplace=True)

# Define columns for rolling averages
rolling_columns = [
    "team_points",
    "point_diff",
    "pts",
    "pie",
    "field_goals_made",
    "field_goals_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_pointers_attempted",
    "three_point_percentage",
    "free_throws_made",
    "free_throws_attempted",
    "free_throw_percentage",
    "effective_field_goal_percentage",
    "true_shooting_percentage",
    "oreb",
    "dreb",
    "reb",
    "offensive_rebound_percentage",
    "defensive_rebound_percentage",
    "rebound_percentage",
    "ast",
    "assist_percentage",
    "assist_ratio",
    "assist_to_turnover",
    "stl",
    "blk",
    "turnover",
    "turnover_ratio",
    "pf",
    "pace",
    "net_rating",
    "offensive_rating",
    "defensive_rating",
    "usage_percentage"
]

# Use transform to ensure alignment with the original DataFrame
for col in rolling_columns:
    team_aggregated_df[f"{col}_rolling15"] = (
        team_aggregated_df.groupby("team_id")[col]
        .transform(lambda x: x.shift(1).rolling(window=15, min_periods=1).mean())
    )


# Inspect results
team_aggregated_df.tail(10)

,game_id,date,season,team_id,team_name,is_home_game,game_postseason,game_won,team_points,point_diff,...,stl_rolling15,blk_rolling15,turnover_rolling15,turnover_ratio_rolling15,pf_rolling15,pace_rolling15,net_rating_rolling15,offensive_rating_rolling15,defensive_rating_rolling15,usage_percentage_rolling15
11897,15908530.0,2025-02-21,2024,30,Washington Wizards,True,0,0.0,101.0,3.0,...,6.600000,3.933333,14.133333,7.111579,19.200000,80.223605,-10.273574,78.994702,89.266551,0.142741
11927,15908546.0,2025-02-23,2024,30,Washington Wizards,False,0,0.0,90.0,20.0,...,6.866667,4.066667,14.200000,7.599357,19.200000,81.991883,-10.523019,79.942480,90.461551,0.147335
11943,15908555.0,2025-02-24,2024,30,Washington Wizards,True,0,1.0,107.0,8.0,...,6.800000,4.266667,14.466667,7.591516,19.666667,80.337404,-10.045939,79.176353,89.218345,0.144787
11975,15908570.0,2025-02-26,2024,30,Washington Wizards,True,0,0.0,121.0,8.0,...,6.733333,4.266667,15.333333,8.262285,20.200000,80.519995,-6.583751,81.607464,88.186687,0.144892
12017,15908591.0,2025-03-01,2024,30,Washington Wizards,False,0,1.0,113.0,13.0,...,6.400000,4.733333,15.600000,8.675755,20.533333,81.685547,-6.252879,82.316114,88.562618,0.144987
12049,15908608.0,2025-03-03,2024,30,Washington Wizards,False,0,0.0,90.0,16.0,...,6.666667,4.866667,16.066667,8.837422,20.066667,82.422603,-5.662324,82.346114,88.002618,0.145248
12083,15908625.0,2025-03-05,2024,30,Washington Wizards,True,0,1.0,125.0,3.0,...,6.866667,4.666667,16.200000,8.868374,20.200000,82.076091,-4.328276,81.901887,86.225595,0.145230
12127,15908646.0,2025-03-08,2024,30,Washington Wizards,False,0,1.0,118.0,1.0,...,7.066667,5.133333,15.133333,8.054068,20.000000,81.948147,-3.739526,83.041887,86.777956,0.145098
12167,15908663.0,2025-03-10,2024,30,Washington Wizards,False,0,0.0,104.0,15.0,...,7.600000,5.200000,15.266667,8.005432,20.000000,82.177757,-2.087102,84.363365,86.447615,0.145650
12175,15908672.0,2025-03-11,2024,30,Washington Wizards,False,0,0.0,103.0,20.0,...,7.466667,5.600000,14.733333,7.811490,19.933333,80.563513,-2.705948,84.581666,87.284442,0.146837

In [22]:
team_aggregated_df.sort_values(by=["date"], inplace=True)

team_aggregated_df.tail(10)

,game_id,date,season,team_id,team_name,is_home_game,game_postseason,game_won,team_points,point_diff,...,stl_rolling15,blk_rolling15,turnover_rolling15,turnover_ratio_rolling15,pf_rolling15,pace_rolling15,net_rating_rolling15,offensive_rating_rolling15,defensive_rating_rolling15,usage_percentage_rolling15
12188,15908800.0,2025-03-28,2024,28,Toronto Raptors,True,0,NaN,NaN,NaN,...,7.866667,3.866667,13.533333,6.707281,21.466667,72.391488,-3.811088,75.763215,79.574727,0.134534
12179,15908804.0,2025-03-28,2024,8,Denver Nuggets,True,0,NaN,NaN,NaN,...,7.000000,4.266667,12.800000,7.211639,18.466667,82.276203,-1.353865,90.715696,92.062654,0.141699
12180,15908798.0,2025-03-28,2024,9,Detroit Pistons,True,0,NaN,NaN,NaN,...,9.666667,5.733333,14.533333,7.486484,21.666667,82.547216,8.099992,91.217544,83.115647,0.151024
12185,15908803.0,2025-03-28,2024,19,New Orleans Pelicans,True,0,NaN,NaN,NaN,...,7.733333,5.333333,13.733333,6.660659,17.400000,70.460560,-3.376436,77.657305,81.035774,0.128531
12184,15908802.0,2025-03-28,2024,18,Minnesota Timberwolves,True,0,NaN,NaN,NaN,...,8.466667,4.333333,11.400000,6.926250,18.733333,85.922666,-3.388606,89.368747,92.758999,0.147656
12181,15908803.0,2025-03-28,2024,10,Golden State Warriors,False,0,NaN,NaN,NaN,...,10.333333,4.866667,12.600000,7.111992,19.800000,84.855025,4.886332,93.486748,88.593636,0.152161
12183,15908801.0,2025-03-28,2024,17,Milwaukee Bucks,True,0,NaN,NaN,NaN,...,6.933333,3.533333,13.933333,7.922244,17.133333,81.921173,2.864306,82.626914,79.762164,0.135048
12189,15908804.0,2025-03-28,2024,29,Utah Jazz,False,0,NaN,NaN,NaN,...,6.400000,3.666667,16.800000,8.029413,17.933333,71.229546,-5.811806,74.262302,80.074849,0.127054
12178,15908798.0,2025-03-28,2024,6,Cleveland Cavaliers,False,0,NaN,NaN,NaN,...,7.866667,4.133333,13.666667,8.229436,18.400000,84.008642,6.111282,97.413089,91.305223,0.152457
12186,15908801.0,2025-03-28,2024,20,New York Knicks,False,0,NaN,NaN,NaN,...,7.800000,3.933333,12.666667,8.192041,16.866667,86.411150,-3.640393,90.747347,94.391283,0.155589

In [23]:
team_aggregated_df[team_aggregated_df["team_points_rolling15"].isna()].count()

game_id                       30
date                          30
season                        30
team_id                       30
team_name                     30
                              ..
pace_rolling15                 0
net_rating_rolling15           0
offensive_rating_rolling15     0
defensive_rating_rolling15     0
usage_percentage_rolling15     0
Length: 91, dtype: int64

In [24]:
# Organizing columns for readability

# Define the columns that should be moved to the end
columns_to_move = ["absent_players", "team_absent_impact", "days_since_last_game", "game_city", "travel_distance", "win_streak", "team_elo", "opponent_elo",
    "season_elo", "opponent_season_elo", "time_in_season"]

# Get the remaining columns in their current order, excluding the ones to move
remaining_columns = [col for col in team_aggregated_df.columns if col not in columns_to_move]

# Define the new column order
ordered_columns = remaining_columns + columns_to_move

# Apply the new column order to the dataframe
team_aggregated_df = team_aggregated_df[ordered_columns]

### Preparing Team-game dataset for ML model prediction

In [25]:
# Create separate home and away dataframes
home_df = team_aggregated_df[team_aggregated_df["is_home_game"] == True].copy()
away_df = team_aggregated_df[team_aggregated_df["is_home_game"] == False].copy()

# Rename columns to distinguish home and away data
home_df = home_df.add_prefix("home_")
away_df = away_df.add_prefix("away_")

# Merge the two datasets on game_id
merged_games_df = home_df.merge(
    away_df, left_on="home_game_id", right_on="away_game_id", suffixes=("", "")
)

# Drop duplicate columns for game_id
merged_games_df.drop(columns=["away_game_id"], inplace=True)
merged_games_df.rename(columns={"home_game_id": "game_id"}, inplace=True)

merged_games_df

,game_id,home_date,home_season,home_team_id,home_team_name,home_is_home_game,home_game_postseason,home_game_won,home_team_points,home_point_diff,...,away_team_absent_impact,away_days_since_last_game,away_game_city,away_travel_distance,away_win_streak,away_team_elo,away_opponent_elo,away_season_elo,away_opponent_season_elo,away_time_in_season
0,127502.0,2020-12-22,2020,3,Brooklyn Nets,True,0,1.0,125.0,26.0,...,0.0,NaN,Brooklyn,NaN,NaN,1490.000000,1510.000000,1490.000000,1510.000000,1
1,127503.0,2020-12-22,2020,14,Los Angeles Lakers,True,0,0.0,109.0,7.0,...,0.0,NaN,Los Angeles,NaN,NaN,1500.000000,1500.000000,1500.000000,1500.000000,1
2,127513.0,2020-12-23,2020,15,Memphis Grizzlies,True,0,0.0,119.0,12.0,...,0.0,NaN,Memphis,NaN,NaN,1510.000000,1490.000000,1510.000000,1490.000000,2
3,127505.0,2020-12-23,2020,12,Indiana Pacers,True,0,1.0,121.0,14.0,...,0.0,NaN,Indianapolis,NaN,NaN,1490.000000,1510.000000,1490.000000,1510.000000,2
4,127506.0,2020-12-23,2020,22,Orlando Magic,True,0,1.0,113.0,6.0,...,0.0,NaN,Orlando,NaN,NaN,1500.000000,1500.000000,1500.000000,1500.000000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6090,15908804.0,2025-03-28,2024,8,Denver Nuggets,True,0,NaN,NaN,NaN,...,21.0,18.0,Denver,1770.0,-5.0,1273.084144,1677.044607,1279.897180,1666.177974,158
6091,15908798.0,2025-03-28,2024,9,Detroit Pistons,True,0,NaN,NaN,NaN,...,0.0,17.0,Detroit,90.0,14.0,1800.207869,1584.382226,1797.136416,1594.015675,158
6092,15908803.0,2025-03-28,2024,19,New Orleans Pelicans,True,0,NaN,NaN,NaN,...,13.0,18.0,New Orleans,1926.0,4.0,1612.074908,1379.158278,1606.403118,1377.517714,158
6093,15908802.0,2025-03-28,2024,18,Minnesota Timberwolves,True,0,NaN,NaN,NaN,...,16.0,18.0,Minneapolis,699.0,-0.0,1416.905731,1601.108391,1413.221153,1591.074044,158
6094,15908801.0,2025-03-28,2024,17,Milwaukee Bucks,True,0,NaN,NaN,NaN,...,17.0,18.0,Milwaukee,1775.0,0.0,1600.081822,1554.935992,1595.274711,1556.713786,158

In [26]:
# Rename columns and drop duplicates

# Validate that home_date and away_date are the same, then drop one and rename
if (merged_games_df["home_date"] == merged_games_df["away_date"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_date"]).rename(columns={"home_date": "date"})

# Validate that home_season and away_season are the same, then drop one and rename
if (merged_games_df["home_season"] == merged_games_df["away_season"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_season"]).rename(columns={"home_season": "season"})

# Drop home_is_home_game and away_is_home_game as they are redundant
merged_games_df = merged_games_df.drop(columns=["home_is_home_game", "away_is_home_game"])

# Validate that home_game_postseason and away_game_postseason are the same, then drop one and rename
if (merged_games_df["home_game_postseason"] == merged_games_df["away_game_postseason"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_game_postseason"]).rename(columns={"home_game_postseason": "game_postseason"})

# Rename home_game_won and away_game_won for clarity
merged_games_df = merged_games_df.rename(columns={"home_game_won": "home_team_won", "away_game_won": "away_team_won"})

# Rename home team win streaks for clarity
merged_games_df = merged_games_df.rename(columns={"home_win_streak": "home_team_win_streak", "home_loss_streak": "home_team_loss_streak", "home_home_win_streak" : "home_team_home_games_win_streak", "home_away_win_streak" : "home_team_away_games_win_streak"})

# Rename away team win streaks for clarity
merged_games_df = merged_games_df.rename(columns={"away_win_streak": "away_team_win_streak", "away_loss_streak": "away_team_loss_streak", "away_home_win_streak" : "away_team_home_games_win_streak", "away_away_win_streak" : "away_team_away_games_win_streak"})

# Validate that home_game_city and away_game_city are the same, then drop one and rename
if (merged_games_df["home_game_city"] == merged_games_df["away_game_city"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_game_city"]).rename(columns={"home_game_city": "game_city"})

# Validate that away_point_diff and home_point_diff are the same, then drop one and rename
if (merged_games_df["away_point_diff"] == merged_games_df["home_point_diff"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_point_diff"]).rename(columns={"home_point_diff": "point_diff"})

# Validate that away_time_in_season and home_time_in_season are the same, then drop one and rename
if (merged_games_df["away_time_in_season"] == merged_games_df["home_time_in_season"]).all():
    merged_games_df = merged_games_df.drop(columns=["away_time_in_season"]).rename(columns={"home_time_in_season": "time_in_season"})

In [27]:
# Filter rows where game_id matches upcoming games
upcoming_game_ids = upcoming_games["game_id"].unique()
upcoming_game_rows = merged_games_df[merged_games_df["game_id"].isin(upcoming_game_ids)]

# Display result
print(upcoming_game_rows.shape)
upcoming_game_rows.head()

(7, 174)

,game_id,date,season,home_team_id,home_team_name,game_postseason,home_team_won,home_team_points,home_point_diff,home_minutes,...,away_usage_percentage_rolling15,away_absent_players,away_team_absent_impact,away_days_since_last_game,away_travel_distance,away_team_win_streak,away_team_elo,away_opponent_elo,away_season_elo,away_opponent_season_elo
6088,15908799.0,2025-03-28,2024,3,Brooklyn Nets,0,NaN,NaN,NaN,NaN,...,0.133772,4,18.0,17.0,1170.0,-0.0,1498.629696,1361.554800,1494.665083,1371.741290
6089,15908800.0,2025-03-28,2024,28,Toronto Raptors,0,NaN,NaN,NaN,NaN,...,0.110614,0,0.0,18.0,1234.0,1.0,1272.511389,1419.603032,1288.364110,1433.589373
6090,15908804.0,2025-03-28,2024,8,Denver Nuggets,0,NaN,NaN,NaN,NaN,...,0.127054,2,21.0,18.0,1770.0,-5.0,1273.084144,1677.044607,1279.897180,1666.177974
6091,15908798.0,2025-03-28,2024,9,Detroit Pistons,0,NaN,NaN,NaN,NaN,...,0.152457,0,0.0,17.0,90.0,14.0,1800.207869,1584.382226,1797.136416,1594.015675
6092,15908803.0,2025-03-28,2024,19,New Orleans Pelicans,0,NaN,NaN,NaN,NaN,...,0.152161,2,13.0,18.0,1926.0,4.0,1612.074908,1379.158278,1606.403118,1377.517714

### Upcoming Games Outcome Prediction

#### Features

In [28]:
# Define the list of feature columns
feature_cols = [
    "game_postseason",
    "time_in_season",
    
    # Home Rolling Stats & Context
    "home_team_win_streak",
    "home_team_elo",
    "home_opponent_elo",
    "home_pts_rolling15",
    "home_pie_rolling15",
    "home_field_goals_made_rolling15",
    "home_field_goals_attempted_rolling15",
    "home_field_goal_percentage_rolling15",
    "home_three_pointers_made_rolling15",
    "home_three_pointers_attempted_rolling15",
    "home_three_point_percentage_rolling15",
    "home_free_throws_made_rolling15",
    "home_free_throws_attempted_rolling15",
    "home_free_throw_percentage_rolling15",
    "home_effective_field_goal_percentage_rolling15",
    "home_true_shooting_percentage_rolling15",
    "home_oreb_rolling15",
    "home_dreb_rolling15",
    "home_reb_rolling15",
    "home_offensive_rebound_percentage_rolling15",
    "home_defensive_rebound_percentage_rolling15",
    "home_rebound_percentage_rolling15",
    "home_ast_rolling15",
    "home_assist_percentage_rolling15",
    "home_assist_ratio_rolling15",
    "home_assist_to_turnover_rolling15",
    "home_stl_rolling15",
    "home_blk_rolling15",
    "home_turnover_rolling15",
    "home_turnover_ratio_rolling15",
    "home_pf_rolling15",
    "home_pace_rolling15",
    "home_net_rating_rolling15",
    "home_offensive_rating_rolling15",
    "home_defensive_rating_rolling15",
    "home_usage_percentage_rolling15",
    "home_absent_players",
    "home_team_absent_impact",
    "home_days_since_last_game",
    "home_travel_distance",
    
    # Away Rolling Stats & Context
    "away_team_win_streak",
    "away_team_elo",
    "away_opponent_elo",
    "away_pts_rolling15",
    "away_pie_rolling15",
    "away_field_goals_made_rolling15",
    "away_field_goals_attempted_rolling15",
    "away_field_goal_percentage_rolling15",
    "away_three_pointers_made_rolling15",
    "away_three_pointers_attempted_rolling15",
    "away_three_point_percentage_rolling15",
    "away_free_throws_made_rolling15",
    "away_free_throws_attempted_rolling15",
    "away_free_throw_percentage_rolling15",
    "away_effective_field_goal_percentage_rolling15",
    "away_true_shooting_percentage_rolling15",
    "away_oreb_rolling15",
    "away_dreb_rolling15",
    "away_reb_rolling15",
    "away_offensive_rebound_percentage_rolling15",
    "away_defensive_rebound_percentage_rolling15",
    "away_rebound_percentage_rolling15",
    "away_ast_rolling15",
    "away_assist_percentage_rolling15",
    "away_assist_ratio_rolling15",
    "away_assist_to_turnover_rolling15",
    "away_stl_rolling15",
    "away_blk_rolling15",
    "away_turnover_rolling15",
    "away_turnover_ratio_rolling15",
    "away_pf_rolling15",
    "away_pace_rolling15",
    "away_net_rating_rolling15",
    "away_offensive_rating_rolling15",
    "away_defensive_rating_rolling15",
    "away_usage_percentage_rolling15",
    "away_absent_players",
    "away_team_absent_impact",
    "away_days_since_last_game",
    "away_travel_distance"
]

#### Predictions

In [29]:
# Make predictions using the trained model
predictions = best_xgb.predict(upcoming_game_rows[feature_cols])

# Create a DataFrame with predictions and game_id for correct mapping
pred_df = pd.DataFrame({
    "game_id": upcoming_game_rows["game_id"].values,
    "predicted_home_win": predictions
})

# Merge predictions into upcoming_games on game_id to ensure correct alignment
upcoming_games = upcoming_games.merge(pred_df, on="game_id", how="left")

# Create a new column 'Predicted_Winner' that displays the winning team name
upcoming_games["predicted_winner"] = np.where(
    upcoming_games["predicted_home_win"] == 1, upcoming_games["home_team"], upcoming_games["away_team"]
)

# Drop the intermediate predicted_home_win column if not needed
upcoming_games = upcoming_games.drop(columns=["predicted_home_win"])

# Display the final DataFrame
upcoming_games

,game_id,date,season,home_team,away_team,game_city,game_postseason,predicted_winner
0,15908799,2025-03-28,2024,Brooklyn Nets,LA Clippers,Brooklyn,False,LA Clippers
1,15908801,2025-03-28,2024,Milwaukee Bucks,New York Knicks,Milwaukee,False,Milwaukee Bucks
2,15908804,2025-03-28,2024,Denver Nuggets,Utah Jazz,Denver,False,Denver Nuggets
3,15908803,2025-03-28,2024,New Orleans Pelicans,Golden State Warriors,New Orleans,False,Golden State Warriors
4,15908802,2025-03-28,2024,Minnesota Timberwolves,Phoenix Suns,Minnesota,False,Minnesota Timberwolves
5,15908798,2025-03-28,2024,Detroit Pistons,Cleveland Cavaliers,Detroit,False,Detroit Pistons
6,15908800,2025-03-28,2024,Toronto Raptors,Charlotte Hornets,Toronto,False,Toronto Raptors